#! /usr/bin/env bash

# x11docker
# Run GUI applications and desktop environments in Docker containers.
#
# - Runs additional X servers to circumvent common X security leaks.
# - Restricts container capabilities to enhance container security.
# - Container user is same as host user to avoid root in container.
# - Features e.g. sound, hardware acceleration and data storage.
#
# Run 'x11docker --help' or scroll down to read usage information.
# More documentation at:  https://github.com/mviereck/x11docker

Version="6.10.0"

# --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
for arg in "$@"; do
  if [ "$arg" = "--enforce-i" ]; then
    echo "forcing interactive mode"
    exec bash --noprofile --norc --noediting -i -- "$0" "$@"
  fi
done

. lib/usage.sh
. lib/license.sh

#### messages
. lib/alertbox.sh
. lib/debugnote.sh
. lib/error.sh
. lib/logentry.sh
. lib/note.sh
. lib/traperror.sh
. lib/verbose.sh
. lib/warning.sh
. lib/watchmessagefifo.sh

#### exit
. lib/finish.sh
. lib/finish_sigint.sh
. lib/saygoodbye.sh

#### watching processes
. lib/checkpid.sh
. lib/containerisrunning.sh
. lib/pspid.sh
. lib/rocknroll.sh
. lib/setonwatchpidlist.sh
. lib/storepid.sh
. lib/termpid.sh
. lib/waitfortheend.sh
. lib/watchpidlist.sh

#### more or less general routines
. lib/askyesno.sh
. lib/check_envvar.sh
. lib/check_parent_sshd.sh
. lib/download.sh
. lib/escapestring.sh
. lib/getrandomnumber.sh
. lib/isnum.sh
. lib/makecookie.sh
. lib/mysleep.sh
. lib/parse_inspect.sh
. lib/storeinfo.sh
. lib/rmcr.sh
. lib/timestamp.sh
. lib/unspecialstring.sh
. lib/verlt.sh
. lib/verlte.sh
. lib/wincmd.sh

#### file routines
. lib/convertpath.sh
. lib/getwslpath.sh
. lib/mkfile.sh
. lib/myrealpath.sh
. lib/waitforlogentry.sh
. lib/writeaccess.sh

#### special jobs of x11docker (not running X or docker)
. lib/buildimage.sh
. lib/cleanup.sh
. lib/create_launcher.sh
. lib/installer.sh

#### features
. lib/check_windowmanager.sh
. lib/clean_xhost.sh
. lib/setup_clipboard.sh
. lib/setup_gpu.sh
. lib/setup_hostdbus.sh
. lib/setup_printer.sh
. lib/setup_sound_alsa.sh
. lib/setup_sound_pulseaudio.sh
. lib/setup_webcam.sh

#### X server setup
. lib/check_newxenv.sh
. lib/check_screensize.sh
. lib/check_vt.sh
. lib/check_xdepends.sh
. lib/check_xpraoption.sh
. lib/check_xserver.sh
. lib/create_xcommand.sh
. lib/disable_xhost.sh
. lib/weston_getoutputname.sh

#### X helper scripts
. lib/create_modelinefile.sh
. lib/create_xdummywrapper.sh
. lib/create_xdummyxorgconf.sh
. lib/create_xinitrc.sh

#### docker command setup
. lib/check_containerhome.sh
. lib/check_containeruser.sh
. lib/create_dockercommand.sh
. lib/setup_capabilities.sh
. lib/setup_initsystem.sh
. lib/store_runoption.sh

#### docker helper scripts
. lib/create_containerrootrc.sh
. lib/create_dockerrc.sh
. lib/create_xtermrc.sh

#### final startup routines
. lib/start_compositor.sh
. lib/start_docker.sh
. lib/start_hostexe.sh
. lib/start_pulseaudiotcp.sh
. lib/start_xpra.sh
. lib/start_xserver.sh

#### main init routines
. lib/check_fallback.sh
. lib/check_host.sh
. lib/check_hostuser.sh
. lib/check_hostxenv.sh
. lib/check_option_interferences.sh
. lib/check_passwordfrontend.sh
. lib/check_runmode.sh
. lib/check_terminalemulator.sh
. lib/create_cachefiles.sh
. lib/drop_cachefiles.sh
. lib/option_messages.sh
. lib/setup_fifo.sh
. lib/setup_verbosity.sh

#### main
. lib/declare_variables.sh
. lib/parse_options.sh
. lib/unpriv.sh
. lib/main.sh

main "$@"
